# Generated by Django 4.0.5 on 2022-07-06 15:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('objetivo', models.TextField()),
                ('idade_minima', models.IntegerField()),
                ('componentes', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Nome'), size=models.IntegerField(verbose_name='Carga Horária')), size=None)),
            ],
        ),
    ]
