# Generated by Django 4.0.5 on 2022-07-06 15:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='componentes',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Nome'), size=models.CharField(verbose_name='Carga Horária')), size=None),
        ),
    ]
