# Generated by Django 4.0.5 on 2022-07-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_remove_cursos_componentes_alter_cursos_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_componente', models.CharField(max_length=150)),
                ('carga_horaria', models.IntegerField()),
                ('ordem', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Componentes',
        ),
        migrations.AddField(
            model_name='cursos',
            name='componentes',
            field=models.ManyToManyField(related_name='cursos', to='cursos.componente'),
        ),
    ]
