# Generated by Django 4.0.5 on 2022-07-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_componente_delete_componentes_cursos_componentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matriculado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cursos',
            options={'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterField(
            model_name='componente',
            name='carga_horaria',
            field=models.IntegerField(verbose_name='Carga horária'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='nome_componente',
            field=models.CharField(max_length=150, verbose_name='Nome do componente'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='componentes',
            field=models.ManyToManyField(related_name='cursos', to='cursos.componente', verbose_name='Componentes'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='idade_minima',
            field=models.IntegerField(verbose_name='Idade mínima'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome do curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='objetivo',
            field=models.TextField(verbose_name='Objetivo'),
        ),
        migrations.AddField(
            model_name='cursos',
            name='matriculados',
            field=models.ManyToManyField(related_name='matricula', to='cursos.matriculado'),
        ),
    ]
