# Generated by Django 4.0.5 on 2022-07-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_matriculado_alter_cursos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componente',
            options={'ordering': ['ordem']},
        ),
        migrations.AddField(
            model_name='componente',
            name='arquivo',
            field=models.FileField(null=True, upload_to='pdf/', verbose_name='Atividade'),
        ),
    ]
