# Generated by Django 4.0.5 on 2022-07-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_remove_atividades_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='arquivo',
            field=models.ManyToManyField(related_name='matriculados', to='cursos.atividades', verbose_name='Atividades'),
        ),
    ]
