# Generated by Django 4.0.5 on 2022-07-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_alter_componente_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividades',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.matriculado'),
        ),
    ]
