# Generated by Django 4.0.5 on 2022-07-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_atividades_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='arquivo',
            field=models.FileField(upload_to='uploads/', verbose_name='Atividade'),
        ),
        migrations.AlterField(
            model_name='atividades',
            name='usuario',
            field=models.IntegerField(null=True, verbose_name='Id do usuário'),
        ),
    ]
