# Generated by Django 4.0.5 on 2022-07-09 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_alter_atividades_arquivo_alter_atividades_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividades',
            old_name='usuario',
            new_name='id_usuario',
        ),
    ]
