# Generated by Django 4.0.5 on 2022-07-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_atividades_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='status',
            field=models.TextField(choices=[('AGUARDANDO_AVALIACAO', 'Aguardando avaliação'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], default=0, null=True, verbose_name='Status'),
        ),
    ]
