# Generated by Django 4.0.5 on 2022-07-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_alter_atividades_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividades',
            name='id_componente',
            field=models.IntegerField(null=True, verbose_name='Id do componente'),
        ),
    ]
