# Generated by Django 4.0.5 on 2022-07-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0016_atividades_id_componente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividades',
            name='id_componente',
        ),
        migrations.AddField(
            model_name='atividades',
            name='nome_componente',
            field=models.IntegerField(null=True, verbose_name='Nome do componente'),
        ),
        migrations.AddField(
            model_name='atividades',
            name='nome_usuario',
            field=models.CharField(max_length=150, null=True, verbose_name='Nome do aluno'),
        ),
    ]
