# Generated by Django 4.0.5 on 2022-07-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0017_remove_atividades_id_componente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='nome_componente',
            field=models.CharField(max_length=150, null=True, verbose_name='Nome do componente'),
        ),
    ]
