# Generated by Django 4.0.5 on 2022-07-10 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0019_atividades_nome_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividades',
            name='nome_curso',
        ),
    ]
