# Generated by Django 4.0.5 on 2022-07-10 23:50

import cursos.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0020_remove_atividades_nome_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='arquivo',
            field=models.FileField(upload_to='uploads/', validators=[cursos.validation.file_size], verbose_name='Atividade'),
        ),
    ]
