# Generated by Django 4.0.5 on 2022-07-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuarios_email_alter_usuarios_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name_plural': 'Usuários'},
        ),
    ]
