# Generated by Django 4.0.5 on 2022-07-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuarios_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='indica_privacidade',
            field=models.TextField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='Aguardando avaliação', max_length=3, verbose_name='Privacidade'),
        ),
    ]
